version: "2"

services:

  bot:
    build: ./bot
    restart: always
    command: python3 main.py

  web:
    build: ./web
    restart: always
    command: gunicorn main:main --timeout 86400 -w 5 --bind 0.0.0.0:8080 --worker-class aiohttp.GunicornWebWorker
    ports:
      - 8080:8080

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on: 
      - web